---
title: "現存量"
author: "Yuki Kanamori"
date: "2021/8/27"
output: 
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
require(tidyverse)
require(openxlsx)

# directory -----------------------------------------------------
dir_input = "/Users/Yuki/Dropbox/業務/若鷹丸調査結果まとめ_東北底魚研究/2020年度/input"
dir_output = "/Users/Yuki/Dropbox/業務/若鷹丸調査結果まとめ_東北底魚研究/2020年度/output"

# not change
knitr::opts_chunk$set(echo = TRUE)
options(warn = -1)
```


```{r make_table, echo=F, warning=F, message=F, results=F}
# data ----------------------------------------------------------
old = NULL
for(i in 1:(2018-1995+1)){
  temp = read.xlsx(paste0(dir_input, "/1_1995～2018資源尾数、重量グラフ.xlsx"), sheet = i, startRow = 1)
  
  if(i < 12){
    temp = temp[, c(1:5, 7:9)]
    temp = temp %>% na.omit() %>% filter(南北 != "南北計")
  }else{
    temp = temp[, 1:8]
    temp = temp %>% na.omit() %>% filter(南北 != "南北計")
  }

  old = rbind(old, temp)
}

y19 = read.xlsx(paste0(dir_input, "/q_資源量合計クエリ2019.xlsx"), sheet = 1, startRow = 1) %>% na.omit() %>% filter(南北 != "南北計")
y20 = read.xlsx(paste0(dir_input, "/q_資源量合計クエリ2020.xlsx"), sheet = 1, startRow = 1) %>% na.omit() %>% filter(南北 != "南北計")

all = rbind(old, y19, y20)
all = all %>% mutate(year = as.numeric(str_sub(調査種類名称, 1, 4)), NS = str_sub(南北, 1, 1)) %>% dplyr::rename(data = "尾数・重量", sp = "和名", sum = "資源量計") %>% select(year, NS, data, sp, sum)
ns = data.frame(NS = c("N", "S"), 南北 = c("北部", "南部"))
all = left_join(all, ns, by = "NS") %>% select(-NS) %>% dplyr::rename(NS = 南北)
all$NS = factor(all$NS, levels = c("北部", "南部"))
all = all %>% mutate(data = ifelse(all$data == "資源重量", "重量", "尾数"))
unique(all$sp)
sp_list = unique(all$sp)
# levels(sp_list)
# sp_list = factor(sp_list, levels = c("スケトウダラ０＋", "スケトウダラ１＋", "マダラ０＋", "マダラ１＋", "マダラ２＋", "イトヒキダラ",  "キチジ", "ズワイガニ雌", "ズワイガニ雄", "スルメイカ", "ベニズワイ雌", "ベニズワイ雄", "アカガレイ", "サメガレイ", "ババガレイ",  "キアンコウ"))

biomass = all %>% filter(data == "重量") %>% dplyr::group_by(year, sp) %>% dplyr::summarize(トン = sum(sum)/1000) %>% dplyr::rename(年 = year, 魚種 = sp)
numbers = all %>% filter(data == "尾数") %>% dplyr::group_by(year, sp) %>% dplyr::summarize(尾 = sum(sum)) %>% dplyr::rename(年 = year, 魚種 = sp)

for(i in 1:length(sp_list)){
  assign(paste("mass", i, sep = ""),
         biomass %>% filter(魚種 == sp_list[i])
         )
}

for(i in 1:length(sp_list)){
  assign(paste("n", i, sep = ""),
         numbers %>% filter(魚種 == sp_list[i])
         )
}
  
```

```{r biomass, echo=F}
mass1
mass2
mass3
mass4
mass11
mass5
mass6
mass12
mass13
mass7
mass14
mass15
mass8
mass9
mass10
mass16
```
